name: XQUnit Tests
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
    
    - name: Install BaseX
      run: |
        wget https://files.basex.org/releases/12.4/BaseX124.zip
        unzip BaseX119.zip

    - name: Start BaseX HTTP Server
      run: |
        ./basex/bin/basexhttp &

    - name: Prepare test
      run: |
        bash scripts/project_create.sh --basex_path './basex/bin' --project_dir_path 'data_test/encpos_by_abstract' --top_collection_id 'test' --db_name 'test'
    - name: Run tests
      run: |
        ./basex/bin/basex -b dbName=test -b projectDirPath=data_test/encpos_by_abstract -b topCollectionId=test -b option='false()' -W -o xqunit.xml -t tests/project_create/
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: xqunit
        path: xqunit.xml
